INSERT INTO MUSIC VALUES (1,'The 2nd Law','Muse','Madness');
INSERT INTO MUSIC VALUES (2,'3-1','Prototyperaptor','Weapon of Mass Refunktion');
INSERT INTO MUSIC VALUES (3,'09/17 2007 - EP','Danger','3h16');
INSERT INTO MUSIC VALUES (4,'21st Century Breakdown','Green Day','21st Century Breakdown');
INSERT INTO MUSIC VALUES (5,'21st Century Breakdown','Green Day','Know Your Enemy');
INSERT INTO MUSIC VALUES (6,'21st Century Breakdown','Green Day','Christian''s Inferno');
INSERT INTO MUSIC VALUES (7,'21st Century Breakdown','Green Day','21 Guns');
INSERT INTO MUSIC VALUES (8,'50,000 Watts EP','Calvertron','50K (Original Mix)');
INSERT INTO MUSIC VALUES (9,'50 Shades of Dubstep','K-Step','Gangnam Style (Electro Dubstep Remix)');
INSERT INTO MUSIC VALUES (10,'99 Problems / Dirt Off Your Shoulder','JAY Z','99 Problems');
INSERT INTO MUSIC VALUES (11,'100 Dubstep - Club Tracks','Dubstep','Kernkraft 400 (Dubstep Remix)');
INSERT INTO MUSIC VALUES (12,'100% No Modern Talking','Knife Party','Internet Friends');
INSERT INTO MUSIC VALUES (13,'1837','Mats GulbrandsenChimeric','1837 - Original Mix');
INSERT INTO MUSIC VALUES (14,'2001','Dr. DreSnoop Dogg','The Next Episode');
INSERT INTO MUSIC VALUES (15,'The 2nd Law','Muse','Panic Station');
INSERT INTO MUSIC VALUES (16,'A*S*Y*S - Bassturbation Remixes','A*S*Y*S','Bassturbation - Oyaebu Remix');
INSERT INTO MUSIC VALUES (17,'Absolution','Muse','Time Is Running Out');
INSERT INTO MUSIC VALUES (18,'Acid Wolfpack','Coyote Kisses','Acid Wolfpack - Original Mix');
INSERT INTO MUSIC VALUES (19,'Action','Uppermost','Futur');
INSERT INTO MUSIC VALUES (20,'The Added Fat EP','The Prodigy','Smack My Bitch Up (Major Lazer Remix)');
INSERT INTO MUSIC VALUES (21,'The Adventures of Mr. Fox EP','Koan Sound','80s Fitness - Original Mix');
INSERT INTO MUSIC VALUES (22,'The Adventures of Mr. Fox EP','Koan Sound','Sly Fox - Original Mix');
INSERT INTO MUSIC VALUES (23,'The Adventures of Mr. Fox EP','Koan Sound','Eastern Thug - Neosignal Remix');
INSERT INTO MUSIC VALUES (24,'After Hours','OVERWERK','Relapse');
INSERT INTO MUSIC VALUES (25,'Afterlife','Avenged Sevenfold','Afterlife');
INSERT INTO MUSIC VALUES (26,'Aftershock','Schoolboy','Aftershock');
INSERT INTO MUSIC VALUES (27,'Alien Technologies','The Damn Bell DoorsMitis','Alien Technologies - Mitis Remix');
INSERT INTO MUSIC VALUES (28,'All In','Dubba Jonny','A Brief Tutorial On Vip Production (Vip) - Vip');
INSERT INTO MUSIC VALUES (29,'All Killer, No Filler','Sum 41','Fat Lip');
INSERT INTO MUSIC VALUES (30,'All Killer, No Filler','Sum 41','In Too Deep');
INSERT INTO MUSIC VALUES (31,'All The Cash','Evil NineEl-P','All The Cash - The Glitch Mob Remix');
INSERT INTO MUSIC VALUES (32,'All The Right Reasons','Nickelback','Animals');
INSERT INTO MUSIC VALUES (33,'Alpha Centauri','Noisia','Alpha Centauri - Excision & Datsik Remix');
INSERT INTO MUSIC VALUES (34,'Always Outnumbered, Never Outgunned','The Prodigy','Spitfire');
INSERT INTO MUSIC VALUES (35,'Always Outnumbered, Never Outgunned','The Prodigy','Action Radar');
INSERT INTO MUSIC VALUES (36,'American Idiot','Green Day','American Idiot');
INSERT INTO MUSIC VALUES (37,'An-ten-nae Presents Acid Crunk Vol. 4','Griz','I''m Home');
INSERT INTO MUSIC VALUES (38,'Android Porn / Steppin'' Razor - Single','Kraddy','Steppin'' Razor');
INSERT INTO MUSIC VALUES (39,'Android Porn Remixes','Kraddy','Android Porn - Mochipet Godzillaporn Remix');
INSERT INTO MUSIC VALUES (40,'Android Porn Remixes','Kraddy','Android Porn - Playpad Circus Remix');
INSERT INTO MUSIC VALUES (41,'Animal Vegetable Mineral - Part 1','Doctor PCecile Charlton','Flying Spaghetti Monster');
INSERT INTO MUSIC VALUES (42,'Animal Vegetable Mineral - Part 1','Doctor PCecile Charlton','Bulletproof - feat. Eva Simons');
INSERT INTO MUSIC VALUES (43,'Animale','Don DiabloDragonette','Animale - Datsik Remix');
INSERT INTO MUSIC VALUES (44,'Animals','Martin Garrix','Animals - Radio Edit');
INSERT INTO MUSIC VALUES (45,'Annihilation','Nom De StripWiwek','Annihilation - Original Club Mix');
INSERT INTO MUSIC VALUES (46,'Anthems of the Hero','Kraddy','The Holy Avenger');
INSERT INTO MUSIC VALUES (47,'Anthems of the Hero','Kraddy','Heart Anthem');
INSERT INTO MUSIC VALUES (48,'Antichrist Superstar','Marilyn Manson','The Beautiful People');
INSERT INTO MUSIC VALUES (49,'Antigravity','Zircon','Warhead');
INSERT INTO MUSIC VALUES (50,'Apex','Foreign Beggars','Apex - Original Mix');
INSERT INTO MUSIC VALUES (51,'Appetite For Destruction','Guns N'' Roses','Paradise City');
INSERT INTO MUSIC VALUES (52,'The Arcade','Ac3','Modern Wargasm');
INSERT INTO MUSIC VALUES (53,'Around The World','Atlas Plug','Around The World');
INSERT INTO MUSIC VALUES (54,'Audioslave','Audioslave','Show Me How to Live');
INSERT INTO MUSIC VALUES (55,'Ave LLama','Llamatron','Unstable Swings - Original Mix');
INSERT INTO MUSIC VALUES (56,'Bad Meaning Good EP','Dodge & Fuski','Got 2 Come Together');
INSERT INTO MUSIC VALUES (57,'Bad Meaning Good EP','Dodge & Fuski','Turn It Up!');
INSERT INTO MUSIC VALUES (58,'Ballistic','Skorge','Ballistic');
INSERT INTO MUSIC VALUES (59,'Bangarang EP','Skrillex','Right In');
INSERT INTO MUSIC VALUES (60,'Bangarang EP','Skrillex','Bangarang - feat. Sirah');
INSERT INTO MUSIC VALUES (61,'Bangarang EP','SkrillexThe DoorsRobby KriegerRay Manzarek','Breakn'' A Sweat');
INSERT INTO MUSIC VALUES (62,'Bangarang EP','SkrillexWolfgang Gartner','The Devil''s Den');
INSERT INTO MUSIC VALUES (63,'Bangarang EP','Skrillex12th PlanetKill The Noise','Right On Time');
INSERT INTO MUSIC VALUES (64,'Bangarang EP','Skrillex','Kyoto - feat. Sirah');
INSERT INTO MUSIC VALUES (65,'Bangarang EP','Skrillex','Summit - feat. Ellie Goulding');
INSERT INTO MUSIC VALUES (66,'Bass Addiction','Enigma Dubz','Bassment - Original Mix');
INSERT INTO MUSIC VALUES (67,'Bass Cannon','Flux Pavilion','Bass Cannon');
INSERT INTO MUSIC VALUES (68,'Bass Down Low: The Remixes','DEVThe Cataracs','Bass Down Low - Proper Villains Remix');
INSERT INTO MUSIC VALUES (69,'The Battle Of Los Angeles','Rage Against The Machine','Testify');
INSERT INTO MUSIC VALUES (70,'Beggin','Domgue','Beggin - Original Mix');
INSERT INTO MUSIC VALUES (71,'The Best Damn Thing','Avril Lavigne','Girlfriend - Radio Edit');
INSERT INTO MUSIC VALUES (72,'Best Of','Vanessa Carlton','A Thousand Miles');
INSERT INTO MUSIC VALUES (73,'The Big Bang Remixes EP','HirsheeKillaGrahamSue Cho','Hold On To Love - KillaGraham Remix');
INSERT INTO MUSIC VALUES (74,'Big Beat Orchestra','Network Music Ensemble','The Heart of a Champion');
INSERT INTO MUSIC VALUES (75,'Big Fat','TonicTarantula Man','Big Fat - Radio Edit');
INSERT INTO MUSIC VALUES (76,'Big Knobbler','Nom De StripPeo De Pitte','Big Knobbler - Original Mix');
INSERT INTO MUSIC VALUES (77,'Billy Talent II','Billy Talent','This Suffering');
INSERT INTO MUSIC VALUES (78,'The Black and White album','The Hives','Tick Tick Boom');
INSERT INTO MUSIC VALUES (79,'Black Magic','Kill The Noise','Black Magic (Kill The Noise Pt. 2)');
INSERT INTO MUSIC VALUES (80,'Black Magic','Kill The NoiseMercedes','Jump Ya Body - Dub Mix');
INSERT INTO MUSIC VALUES (81,'Black Magic','Kill The Noise','Rockers');
INSERT INTO MUSIC VALUES (82,'Black Magic','Kill The NoiseFeed Me','Thumbs Up');
INSERT INTO MUSIC VALUES (83,'blink-182','blink-182','I Miss You');
INSERT INTO MUSIC VALUES (84,'Blood','In This Moment','Blood');
INSERT INTO MUSIC VALUES (85,'Blow The Roof','Flux Pavilion','Double Edge - feat. Sway and P Money');
INSERT INTO MUSIC VALUES (86,'Blow The Roof','Flux Pavilion','Blow The Roof');
INSERT INTO MUSIC VALUES (87,'Blue Crush Soundtrack','N.E.R.D.','Rock Star - Jason Nevins Remix Edit');
INSERT INTO MUSIC VALUES (88,'Blur','Blur','Song 2');
INSERT INTO MUSIC VALUES (89,'Body Of War: Songs That Inspired An Iraq War Veteran','Rage Against The Machine','Guerilla Radio');
INSERT INTO MUSIC VALUES (90,'Boombox / One Two','Kairo Kingdom','Boombox - Original Mix');
INSERT INTO MUSIC VALUES (91,'Boombox / One Two','Kairo Kingdom','One Two - Original Mix');
INSERT INTO MUSIC VALUES (92,'Borderlands 2: Original Soundtrack','Jesper Kyd','Glacial');
INSERT INTO MUSIC VALUES (93,'Boulevard Of Broken Dreams','Green Day','Boulevard Of Broken Dreams');
INSERT INTO MUSIC VALUES (94,'The Boy With The Digital Heart','Pixelh8','Chocolate Milk');
INSERT INTO MUSIC VALUES (95,'Break Up','Pete YornScarlett Johansson','Relator');
INSERT INTO MUSIC VALUES (96,'Breakdown EP','Document One','Clap');
INSERT INTO MUSIC VALUES (97,'Brick','DaVIP','Brick - Original Mix');
INSERT INTO MUSIC VALUES (98,'Broken Angels','SyrebralxKore','Broken Angels - xKore Remix');
INSERT INTO MUSIC VALUES (99,'Bubblin'' In The Cut / Lobegrinder - Single','Boreta','Bubblin'' In The Cut');
INSERT INTO MUSIC VALUES (100,'Bubblin'' In The Cut / Lobegrinder - Single','Boreta','Lobegrinder');
INSERT INTO MUSIC VALUES (101,'By The Way','Red Hot Chili Peppers','By The Way');
INSERT INTO MUSIC VALUES (102,'By The Way','Red Hot Chili Peppers','Can''t Stop');
INSERT INTO MUSIC VALUES (103,'Californication','Red Hot Chili Peppers','Parallel Universe');
INSERT INTO MUSIC VALUES (104,'Californication (Deluxe Version)','Red Hot Chili Peppers','Otherside');
INSERT INTO MUSIC VALUES (105,'Can Be Late','Skip the Use','Ghost');
INSERT INTO MUSIC VALUES (106,'Can''t Hardly Wait','blink-182','Dammit');
INSERT INTO MUSIC VALUES (107,'Careless - EP','Jack BeatsDiploExample','War - Original');
INSERT INTO MUSIC VALUES (108,'Careless - EP','Dillon FrancisJack Beats','Epidemic - Original');
INSERT INTO MUSIC VALUES (109,'Carnival','Mojo','Carnival');
INSERT INTO MUSIC VALUES (110,'Cause of Death','Obituary','Cause Of Death - Reissue');
INSERT INTO MUSIC VALUES (111,'The Chase','Just Jawsh','The Chase - Original Mix');
INSERT INTO MUSIC VALUES (112,'Chocolate Starfish And The Hot Dog Flavored Water','Limp Bizkit','Rollin'' (Air Raid Vehicle)');
INSERT INTO MUSIC VALUES (113,'Chuck','Sum 41','Pieces');
INSERT INTO MUSIC VALUES (114,'Chunk of Change','Passion Pit','Sleepyhead');
INSERT INTO MUSIC VALUES (115,'Circus One presented by Dr P and Flux Pavilion','Doctor P','Watch Out');
INSERT INTO MUSIC VALUES (116,'Citizen','Army Of Me','Going Through Changes');
INSERT INTO MUSIC VALUES (117,'The Clarence Greenwood Recordings','Citizen Cope','Bullet and a Target');
INSERT INTO MUSIC VALUES (118,'Clarity','ZeddMatthew Koma','Spectrum');
INSERT INTO MUSIC VALUES (119,'Classics','Ratatat','Montanita');
INSERT INTO MUSIC VALUES (120,'Classics','Ratatat','Lex');
INSERT INTO MUSIC VALUES (121,'Classics','Ratatat','Gettysburg');
INSERT INTO MUSIC VALUES (122,'Classics','Ratatat','Wildcat');
INSERT INTO MUSIC VALUES (123,'Classics','Ratatat','Tropicana');
INSERT INTO MUSIC VALUES (124,'Classics','Ratatat','Loud Pipes');
INSERT INTO MUSIC VALUES (125,'Classics','Ratatat','Kennedy');
INSERT INTO MUSIC VALUES (126,'Classics','Ratatat','Swisha');
INSERT INTO MUSIC VALUES (127,'Classics','Ratatat','Nostrand');
INSERT INTO MUSIC VALUES (128,'Classics','Ratatat','Tacobel Canon');
INSERT INTO MUSIC VALUES (129,'The Cloud EP','Tha Trickaz','Robbery Song');
INSERT INTO MUSIC VALUES (130,'Clouds EP: Vol 2','Nom De Strip','Techno Saturday - Original Mix');
INSERT INTO MUSIC VALUES (131,'Coco Part 2','Parov Stelar','The Mojo Radio Gang (Radioversion)');
INSERT INTO MUSIC VALUES (132,'Coloris','she','Coloris');
INSERT INTO MUSIC VALUES (133,'Comatose','Skillet','Rebirthing');
INSERT INTO MUSIC VALUES (134,'Comatose','Skillet','Comatose');
INSERT INTO MUSIC VALUES (135,'Comatose','Skillet','Falling Inside The Black');
INSERT INTO MUSIC VALUES (136,'Conspiracy Pt.2','Gesaffelstein','Viol - Original Mix');
INSERT INTO MUSIC VALUES (137,'Control','Benny Benassi','Control - feat. Gary Go - Jacob Plant Remix');
INSERT INTO MUSIC VALUES (138,'Cowboy Remixes','Zeds DeadOmar LinX','Cowboy - Congorock Remix');
INSERT INTO MUSIC VALUES (139,'Crazy B Selects, Vol. III','Birdy Nam Nam','Goin'' In (Skrillex Goin Down Remix)');
INSERT INTO MUSIC VALUES (140,'Cross the Line','Camo & KrookedTC','Get Dirty');
INSERT INTO MUSIC VALUES (141,'Crystal Castles (II)','Crystal Castles','Baptism');
INSERT INTO MUSIC VALUES (142,'Curriculum Vitae','Professor Kliq','Crystals');
INSERT INTO MUSIC VALUES (143,'Cypress x Rusko EP','Cypress HillRusko','Shots Go Off');
INSERT INTO MUSIC VALUES (144,'D.R.E.A.M','The Noisy Freaks','D.R.E.A.M - Dead C.A.T Bounce Remix');
INSERT INTO MUSIC VALUES (145,'Dada Life''s Musical Freedom','TJRSue ChoNom De Strip','My Life (Original Mix)');
INSERT INTO MUSIC VALUES (146,'Dancefloor FG Eté / Summer 2012','Avicii','Levels - Skrillex Remix');
INSERT INTO MUSIC VALUES (147,'Dancefloor FG Eté / Summer 2012','Hardwell','Spaceman - Extended');
INSERT INTO MUSIC VALUES (148,'The Day I Die','South Central','The Day I Die - The Qemists Remix');
INSERT INTO MUSIC VALUES (149,'The Dead Symphonic EP','Zomboy','Nuclear (Hands Up)');
INSERT INTO MUSIC VALUES (150,'The Dead Symphonic EP','Zomboy','Hoedown');
INSERT INTO MUSIC VALUES (151,'The Dead Symphonic EP','Zomboy','Vancouver Beatdown');
INSERT INTO MUSIC VALUES (152,'Deadringer: Deluxe','RJD2','Ghostwriter');
INSERT INTO MUSIC VALUES (153,'Death By Robot','Feed Me','Gravel - Original Mix');
INSERT INTO MUSIC VALUES (154,'Death To The Pixies','Pixies','Where Is My Mind?');
INSERT INTO MUSIC VALUES (155,'Demon Days','Gorillaz','Feel Good Inc');
INSERT INTO MUSIC VALUES (156,'Desire','Al BizzareAlateya','Desire - Original Mix');
INSERT INTO MUSIC VALUES (157,'Destroyer of Speakers EP','F.O.O.L','Destroyer of Speakers');
INSERT INTO MUSIC VALUES (158,'The Destruction Series Vol 1','Figure','The Brink - Original Mix');
INSERT INTO MUSIC VALUES (159,'Devils Playground-Prototype','CalvertronMessinian','Prototype (Original mix)');
INSERT INTO MUSIC VALUES (160,'Die For You','Cutline','Die For You');
INSERT INTO MUSIC VALUES (161,'Digital Freedom','Gramatik','Talkbox Intended');
INSERT INTO MUSIC VALUES (162,'#digitalfreedom','Gramatik','Fist Up');
INSERT INTO MUSIC VALUES (163,'#digitalfreedom','Gramatik','Illusion of Choice');
INSERT INTO MUSIC VALUES (164,'Dim Mak Records New Noise Vol. 1','Nom De StripSue ChoTJR','My Life');
INSERT INTO MUSIC VALUES (165,'Dinosaurs Love 808s - EP','Jomekka','Eighto');
INSERT INTO MUSIC VALUES (166,'Diplomatic Immunity','The Polish Ambassador','Earth Versus The World');
INSERT INTO MUSIC VALUES (167,'DIRTY','Dirtyphonics','DIRTY (Original Mix)');
INSERT INTO MUSIC VALUES (168,'Dirty/Clean','Skorge','Hax');
INSERT INTO MUSIC VALUES (169,'Dits From The Commuter Belt','Bromheads Jacket','Fight Music For The Fight');
INSERT INTO MUSIC VALUES (170,'Divergent Spectrum Remix EP','Bassnectar','Upside Down (Bassnectar & Terravita Remix)');
INSERT INTO MUSIC VALUES (171,'Divided By Night','The Crystal Method','Smile?');
INSERT INTO MUSIC VALUES (172,'Division EP','Skism','Experts');
INSERT INTO MUSIC VALUES (173,'Division EP','SkismZomboy','Kick It (feat. Zomboy)');
INSERT INTO MUSIC VALUES (174,'Division EP','SkismZomboy','Kick It (Dirtyloud Remix) [feat. Zomboy]');
INSERT INTO MUSIC VALUES (175,'DIY','Savoy','DIY');
INSERT INTO MUSIC VALUES (176,'DmC Devil May Cry (Original Game Soundtrack) [Bonus Version]','Noisia','Lilith''s Club');
INSERT INTO MUSIC VALUES (177,'Does This Look Infected?','Sum 41','The Hell Song');
INSERT INTO MUSIC VALUES (178,'Does This Look Infected?','Sum 41','Still Waiting');
INSERT INTO MUSIC VALUES (179,'The Dogfight EP','Roksonix','Ride With Me');
INSERT INTO MUSIC VALUES (180,'Doomed','FuntCase','Dem Mans');
INSERT INTO MUSIC VALUES (181,'Dovregubben','Zedd','Dovregubben (Original Mix)');
INSERT INTO MUSIC VALUES (182,'Down The Road','C2C','The Beat');
INSERT INTO MUSIC VALUES (183,'Down With the Kids EP','Skism','Rave Review');
INSERT INTO MUSIC VALUES (184,'Dreamworld','Nightcore','Monster (DotEXE Remix)');
INSERT INTO MUSIC VALUES (185,'Dreamworld','Nightcore','Undead');
INSERT INTO MUSIC VALUES (186,'Drink The Sea','The Glitch Mob','Bad Wings');
INSERT INTO MUSIC VALUES (187,'Drink The Sea','The Glitch Mob','Fistful Of Silence');
INSERT INTO MUSIC VALUES (188,'Drink The Sea','The Glitch Mob','Between Two Points (feat. Swan)');
INSERT INTO MUSIC VALUES (189,'Drink The Sea','The Glitch Mob','Drive It Like You Stole It');
INSERT INTO MUSIC VALUES (190,'Drink The Sea','The Glitch Mob','Fortune Days');
INSERT INTO MUSIC VALUES (191,'Drink the Sea (Remixes Vol. 2)','The Glitch Mob','Bad Wings - Deru Remix');
INSERT INTO MUSIC VALUES (192,'Drive It Like You Stole It - Single','The Glitch Mob','Drive It Like You Stole It');
INSERT INTO MUSIC VALUES (193,'Drop Audio','The Qemists','Stompbox - Spor Remix');
INSERT INTO MUSIC VALUES (194,'Drop It Like It''s Hot','Snoop DoggPharrell Williams','Drop It Like It''s Hot');
INSERT INTO MUSIC VALUES (195,'Droppin Bodies','MineSweepa','Droppin Bodies - Original Mix');
INSERT INTO MUSIC VALUES (196,'Dubstep Electro Glitch','Boys Noize','& Down');
INSERT INTO MUSIC VALUES (197,'Dubstep Essentials','Dubstep','Sandstorm (Dubstep RMX)');
INSERT INTO MUSIC VALUES (198,'Dubstep Onslaught','Nero','This Way - Original Mix');
INSERT INTO MUSIC VALUES (199,'Dubstep Rejectz VOL 1','X SentinelGirlStep','Game Over');
INSERT INTO MUSIC VALUES (200,'Dubstep!!','Chronic Crew','Silver Scrapes');
INSERT INTO MUSIC VALUES (201,'Dubztep','Vegas House','Fake Pulp');
INSERT INTO MUSIC VALUES (202,'E.T. (The Remixes) - EP','Katy Perry','E.T. - Noisia Remix');
INSERT INTO MUSIC VALUES (203,'Earthquake','LabrinthTinie Tempah','Earthquake - Radio Edit');
INSERT INTO MUSIC VALUES (204,'Eject pt. I','CAZZETTE','Run For Cover (Instrumental Mix)');
INSERT INTO MUSIC VALUES (205,'Electric Girl','she','Electric Girl');
INSERT INTO MUSIC VALUES (206,'The Electro Swing Revolution Vol. 2','Parov Stelar','Booty Swing - Original');
INSERT INTO MUSIC VALUES (207,'Elephant Games EP','Mizchief','The Lions Den - Original Mix');
INSERT INTO MUSIC VALUES (208,'Elixir','Mitis','Elixir - Original Mix');
INSERT INTO MUSIC VALUES (209,'The Eminem Show','Eminem','Without Me');
INSERT INTO MUSIC VALUES (210,'The Eminem Show','EminemD12','When The Music Stops');
INSERT INTO MUSIC VALUES (211,'The Eminem Show','EminemHailie Jade','My Dad''s Gone Crazy');
INSERT INTO MUSIC VALUES (212,'The End','12th Planet & Flinch12th PlanetFlinchDirtyphonics','The End Is Near, Pt. 1 - Dirtyphonics Remix');
INSERT INTO MUSIC VALUES (213,'End of The World Party','Griz','Chasin Galaxies');
INSERT INTO MUSIC VALUES (214,'End of The World Party','Griz','Dance With Me');
INSERT INTO MUSIC VALUES (215,'Enema Of The State','blink-182','What''s My Age Again?');
INSERT INTO MUSIC VALUES (216,'Enema Of The State','blink-182','All The Small Things');
INSERT INTO MUSIC VALUES (217,'EP 1','Lets Be Friends','Best in the West');
INSERT INTO MUSIC VALUES (218,'The Essential Korn','Korn','Good God');
INSERT INTO MUSIC VALUES (219,'Everyday','Rusko','Everyday - Netsky Remix');
INSERT INTO MUSIC VALUES (220,'Everyday / Lick The Lizard','Rusko & Reso','Lick The Lizard');
INSERT INTO MUSIC VALUES (221,'Evil Empire','Rage Against The Machine','Bulls on Parade');
INSERT INTO MUSIC VALUES (222,'Evolution','Korn','Evolution');
INSERT INTO MUSIC VALUES (223,'Evolution Theory','ModestepPopeska','Another Day');
INSERT INTO MUSIC VALUES (224,'Evolution Theory (Deluxe Edition)','ModestepD PowerJammin''JammerFrisco','Evolution Theory');
INSERT INTO MUSIC VALUES (225,'Evolution Theory (Deluxe Edition)','Modestep','Freedom');
INSERT INTO MUSIC VALUES (226,'Express Yourself EP','Diplo feat. Billy The Gent & Long JawnsDiploBilly the GentLong Jawns','Butters Theme (feat. Billy The Gent & Long Jawns)');
INSERT INTO MUSIC VALUES (227,'Express Yourself Remix','Diplo feat. Nicky Da BDiploNicky Da BGentJawns','Express Yourself - Gent & Jawns Remix');
INSERT INTO MUSIC VALUES (228,'Eye To The Telescope','KT Tunstall','Black Horse and the Cherry Tree - Radio Version');
INSERT INTO MUSIC VALUES (229,'FantomenK','FantomenK','Goodbye Summer, Hello Winter');
INSERT INTO MUSIC VALUES (230,'FantomenK','FantomenK','Jumo Up and Bounce Down');
INSERT INTO MUSIC VALUES (231,'The Fat Of The Land','The Prodigy','Breathe');
INSERT INTO MUSIC VALUES (232,'The Fat Of The Land','The Prodigy','Firestarter');
INSERT INTO MUSIC VALUES (233,'Feed Me''s Big Adventure','Feed Me','White Spirit - Original Mix');
INSERT INTO MUSIC VALUES (234,'Feed Me''s Big Adventure','Feed Me','Silicone Lube - Original Mix');
INSERT INTO MUSIC VALUES (235,'Feed Me''s Big Adventure','Feed Me','Grand Theft Ecstasy - Original Mix');
INSERT INTO MUSIC VALUES (236,'Feed Me''s Big Adventure','Feed MeTasha Baxter','Cloudburn - Original Mix');
INSERT INTO MUSIC VALUES (237,'Feed Me''s Big Adventure','Feed Me','Blood Red - Original Mix');
INSERT INTO MUSIC VALUES (238,'Feed Me''s Big Adventure','Feed Me','Green Bottle - Original Mix');
INSERT INTO MUSIC VALUES (239,'Feed Me''s Escape From Electric Mountain','Feed Me','One Click Headshot - Original Mix');
INSERT INTO MUSIC VALUES (240,'Fierce / Pornstep','DodgeFuski','Fierce - Original Mix');
INSERT INTO MUSIC VALUES (241,'Finding Beauty In Negative Spaces','Seether','Fake It');
INSERT INTO MUSIC VALUES (242,'Fire','Scooter','Fire');
INSERT INTO MUSIC VALUES (243,'Fire Inside EP','GeminiGreta Svabo Bech','Fire Inside');
INSERT INTO MUSIC VALUES (244,'Fireflies','Razihel','Fireflies - Original Mix');
INSERT INTO MUSIC VALUES (245,'Firestorm EP','Far Too Loud','Firestorm');
INSERT INTO MUSIC VALUES (246,'Firestorm EP','Far Too Loud','Lightbringer');
INSERT INTO MUSIC VALUES (247,'Firestorm EP','Far Too Loud','600 Years');
INSERT INTO MUSIC VALUES (248,'Firestorm EP Remixes','Far Too Loud','Firestorm (Specimen A Remix)');
INSERT INTO MUSIC VALUES (249,'Five Hours','Deorro','Five Hours');
INSERT INTO MUSIC VALUES (250,'Flash That Skin','Oh Shit!Ninetynine','Flash That Skin - Sureshot Remix');
INSERT INTO MUSIC VALUES (251,'Fluorescent Adolescent','Arctic Monkeys','Fluorescent Adolescent');
INSERT INTO MUSIC VALUES (252,'Flyleaf','Flyleaf','Fully Alive');
INSERT INTO MUSIC VALUES (253,'Flyleaf','Flyleaf','Cassie');
INSERT INTO MUSIC VALUES (254,'Flyleaf','Flyleaf','I''m Sorry');
INSERT INTO MUSIC VALUES (255,'Flyleaf','Flyleaf','All Around Me');
INSERT INTO MUSIC VALUES (256,'Flyleaf','Flyleaf','Breathe Today');
INSERT INTO MUSIC VALUES (257,'Fog Bank','Boy 8-BitJack Beats','Fogbank - Jack Beats Remix');
INSERT INTO MUSIC VALUES (258,'Follow The Leader','Korn','Got the Life');
INSERT INTO MUSIC VALUES (259,'Free Volume 4 - EP','Kdrew','Bullseye');
INSERT INTO MUSIC VALUES (260,'Free Volume 4 - EP','Kdrew','Firestarter');
INSERT INTO MUSIC VALUES (261,'Fucking Noise / Digital Controller','Flux Pavilion','Digital Controller');
INSERT INTO MUSIC VALUES (262,'Full Circle','Drowning Pool','Enemy');
INSERT INTO MUSIC VALUES (263,'Funk Blaster','Koan Sound','Funk Blaster');
INSERT INTO MUSIC VALUES (264,'Funk Blaster','Koan Sound','Talk Box');
INSERT INTO MUSIC VALUES (265,'Funk Blaster','Koan Sound','The Edge');
INSERT INTO MUSIC VALUES (266,'Funk Blaster','Koan Sound','Meanwhile, In The Future');
INSERT INTO MUSIC VALUES (267,'Funk Blaster','Koan Sound','Talk Box (Kill The Noise Remix)');
INSERT INTO MUSIC VALUES (268,'Future Sound Theory','Edit','Laundry');
INSERT INTO MUSIC VALUES (269,'Future Sounds EP','Terabyte Frenzy','Kill The Rhythm');
INSERT INTO MUSIC VALUES (270,'Futures','Konec feat. xKoreKonecxKore','Railgun');
INSERT INTO MUSIC VALUES (271,'Game Over','Rednek','Game Over (Calvertron Remix)');
INSERT INTO MUSIC VALUES (272,'Game Time EP','Zomboy','Organ Donor');
INSERT INTO MUSIC VALUES (273,'Gangnam Style (Dubstep Remix)','K-Pop DJ''s','Gangnam Style (Dubstep Remix)');
INSERT INTO MUSIC VALUES (274,'The Geeks And The Jerkin'' Socks','Shaka Ponk','I''m Picky');
INSERT INTO MUSIC VALUES (275,'Get Live / Girlz','Roksonix','Get Live');
INSERT INTO MUSIC VALUES (276,'Ghetto Bass 2','Sub Focus','Last Jungle');
INSERT INTO MUSIC VALUES (277,'Girls EP','Receptor','Girls');
INSERT INTO MUSIC VALUES (278,'Give My Regards','Mitis','Give My Regards - Original Mix');
INSERT INTO MUSIC VALUES (279,'Gives You Hell','The All-American Rejects','Gives You Hell');
INSERT INTO MUSIC VALUES (280,'Good Enough','Brenny Good','Woah Woah Woah (Original Mix)');
INSERT INTO MUSIC VALUES (281,'Good Things','Aloe Blacc','I Need A Dollar');
INSERT INTO MUSIC VALUES (282,'Gorillaz','Gorillaz','Clint Eastwood');
INSERT INTO MUSIC VALUES (283,'Got 2 Know / Normalize','Flux Pavilion','Got 2 Know');
INSERT INTO MUSIC VALUES (284,'Graduation EP','Gemini','Vision');
INSERT INTO MUSIC VALUES (285,'The Great Divide (The Remixes)','Velvetine','The Great Divide - Seven Lions Remix');
INSERT INTO MUSIC VALUES (286,'Greatest Hits','blink-182','Adam''s Song');
INSERT INTO MUSIC VALUES (287,'Greatest Hits, Vol. 1','Korn','Y''all Want a Single');
INSERT INTO MUSIC VALUES (288,'Greatest Hitz','Limp Bizkit','Take A Look Around');
INSERT INTO MUSIC VALUES (289,'Groove Sessions','Chinese Man','I''ve got that tune');
INSERT INTO MUSIC VALUES (290,'Guns Blazin','Professor Kliq','Bust This Bust That');
INSERT INTO MUSIC VALUES (291,'Guns Blazin','Professor Kliq','Guns Blazin''');
INSERT INTO MUSIC VALUES (292,'Guns Blazin','Professor Kliq','Elephantitis');
INSERT INTO MUSIC VALUES (293,'Guns Blazin','Professor Kliq','Ode To Charles');
INSERT INTO MUSIC VALUES (294,'Gutterpump','Noisia','Gutterpump');
INSERT INTO MUSIC VALUES (295,'Half Android','FSCalvertron','Dub Combination - Original Mix');
INSERT INTO MUSIC VALUES (296,'Hallucinations EP','Emenation','Hallucinations - Original Mix');
INSERT INTO MUSIC VALUES (297,'Happy (from Despicable Me 2)','Pharrell Williams','Happy (from Despicable Me 2)');
INSERT INTO MUSIC VALUES (298,'Happy Up Here','Röyksopp','Happy Up Here');
INSERT INTO MUSIC VALUES (299,'The Harder They Fall','Foreign Beggars','Still Getting It Ft. Skrillex');
INSERT INTO MUSIC VALUES (300,'Heads Will Roll (A-Trak Remix)','Yeah Yeah Yeahs','Heads Will Roll - A-Trak Remix');
INSERT INTO MUSIC VALUES (301,'Heat.wav','Robotic Pirate Monkey','Shake n'' Bake');
INSERT INTO MUSIC VALUES (302,'The Heist','Macklemore & Ryan Lewis','Can''t Hold Us - feat. Ray Dalton');
INSERT INTO MUSIC VALUES (303,'Hell Yeah!','Tiësto & Showtek','Hell Yeah!');
INSERT INTO MUSIC VALUES (304,'Hello EP','Going Quantum','Hello (Ephixa Remix)');
INSERT INTO MUSIC VALUES (305,'Here And Now','Nickelback','When We Stand Together');
INSERT INTO MUSIC VALUES (306,'HERE COMES RAKTA EP','RAKTA','HERE COMES RAKTA - Instrumental Mix');
INSERT INTO MUSIC VALUES (307,'Here Comes the Hotstepper (Evian Version)','Baby & Me','Here Comes the Hotstepper - Evian version - Yuksek Remix');
INSERT INTO MUSIC VALUES (308,'Hey Boy Hey Girl','The Chemical Brothers','Hey Boy Hey Girl');
INSERT INTO MUSIC VALUES (309,'Hipster Cutthroat','DotEXE','Hipster Cutthroat');
INSERT INTO MUSIC VALUES (310,'Hobo','Charlie Winston','Kick The Bucket');
INSERT INTO MUSIC VALUES (311,'Hold Your Breath','Street LurkinPopeskaAnna Yvette','Hold Your Breath - Popeska Remix');
INSERT INTO MUSIC VALUES (312,'Holy Wood (In The Shadow Of The Valley Of Death)','Marilyn Manson','The Fight Song');
INSERT INTO MUSIC VALUES (313,'Home','Dubba Jonny','Home - Original Mix');
INSERT INTO MUSIC VALUES (314,'Hot Fuss','The Killers','Mr. Brightside');
INSERT INTO MUSIC VALUES (315,'House Of Pain','House Of Pain','Jump Around');
INSERT INTO MUSIC VALUES (316,'Hypnotize','System Of A Down','Attack');
INSERT INTO MUSIC VALUES (317,'Hypnotize','System Of A Down','Holy Mountains');
INSERT INTO MUSIC VALUES (318,'Hypnotize','System Of A Down','Vicinity Of Obscenity');
INSERT INTO MUSIC VALUES (319,'Hypnotize','System Of A Down','Lonely Day');
INSERT INTO MUSIC VALUES (320,'I Could Be The One [Avicii vs Nicky Romero]','AviciiNicky Romero','I Could Be The One [Avicii vs Nicky Romero] - Nicktim - Radio Edit');
INSERT INTO MUSIC VALUES (321,'I Made This for You EP','Tim Ismag','I Made This for You');
INSERT INTO MUSIC VALUES (322,'I See Monstas','I See MONSTAS','Holdin'' On - Skrillex & Nero Remix');
INSERT INTO MUSIC VALUES (323,'I''m Not Skrillex','Rednek','I''m Not Skrillex - Drumstep Mix');
INSERT INTO MUSIC VALUES (324,'I.D.G.A.F.O.S.','Dillon Francis','I.D.G.A.F.O.S.');
INSERT INTO MUSIC VALUES (325,'Ice Jump','Al Bizzare','Ice Jump - Original Mix');
INSERT INTO MUSIC VALUES (326,'Ignite - EP','Noisestorm','Ignite');
INSERT INTO MUSIC VALUES (327,'The Ill.Methodology','ill.gatesOpiuoVent','TriLLogy');
INSERT INTO MUSIC VALUES (328,'Illegal Bass Mash Up - Dubstep > Garage > Drum & Bass ( Dub Step / Drum n Bass ) (Deluxe Version)','ShockOne','Polygon - Dirtyphonics Remix');
INSERT INTO MUSIC VALUES (329,'Illusions','Approaching Nirvana','Beer Remastered');
INSERT INTO MUSIC VALUES (330,'Immersion','Pendulum','Crush');
INSERT INTO MUSIC VALUES (331,'Immersion','Pendulum','The Island - Pt. II (Dusk)');
INSERT INTO MUSIC VALUES (332,'Immersion','Pendulum','The Vulture');
INSERT INTO MUSIC VALUES (333,'Immersion','Pendulum','Witchcraft');
INSERT INTO MUSIC VALUES (334,'Impulse Prime','Zircon','Hourglass');
INSERT INTO MUSIC VALUES (335,'In My Blood','Kai Wachi','Wrong Decisions - Original Mix');
INSERT INTO MUSIC VALUES (336,'In The Mix','Darude','Sandstorm - (Original Version)');
INSERT INTO MUSIC VALUES (337,'Inception','Quba','Fuck Off');
INSERT INTO MUSIC VALUES (338,'Inception','Quba','From Romania');
INSERT INTO MUSIC VALUES (339,'Ingen Anden Drøm','Pegboard NerdsMorten Breum','Ingen Anden Drøm - XT Edit');
INSERT INTO MUSIC VALUES (340,'Invaders Must Die (Special Edition)','The Prodigy','Invaders Must Die');
INSERT INTO MUSIC VALUES (341,'Invaders Must Die (Special Edition)','The Prodigy','Omen');
INSERT INTO MUSIC VALUES (342,'Invaders Must Die (Special Edition)','The Prodigy','Thunder');
INSERT INTO MUSIC VALUES (343,'Invaders Must Die (Special Edition)','The Prodigy','Colours');
INSERT INTO MUSIC VALUES (344,'Invaders Must Die (Special Edition)','The Prodigy','Take Me to the Hospital');
INSERT INTO MUSIC VALUES (345,'Invasion','F.O.O.L','Invasion');
INSERT INTO MUSIC VALUES (346,'Is This It','The Strokes','Last Nite');
INSERT INTO MUSIC VALUES (347,'Isolated Incidents','Cryptex','Slay It - Original Mix');
INSERT INTO MUSIC VALUES (348,'Isolated Incidents','Cryptex','Go');
INSERT INTO MUSIC VALUES (349,'Jaded Future EP','Birdy Nam Nam','Goin'' In - Skrillex "Goin'' Hard" Mix');
INSERT INTO MUSIC VALUES (350,'Jizz In My Pants','The Lonely Island','Jizz In My Pants');
INSERT INTO MUSIC VALUES (351,'Joe Budden','Joe Budden','Pump It Up');
INSERT INTO MUSIC VALUES (352,'Justice','Justice','Phantom Pt. II');
INSERT INTO MUSIC VALUES (353,'Justice','Justice','Waters Of Nazareth');
INSERT INTO MUSIC VALUES (354,'Karma & Effect','Seether','Remedy');
INSERT INTO MUSIC VALUES (355,'Kick Out The Epic Motherf**ker','Dada Life','Kick Out The Epic Motherf**ker - Datsik Remix');
INSERT INTO MUSIC VALUES (356,'Kill Kill Kill','Kill The Noise','Deal With It');
INSERT INTO MUSIC VALUES (357,'Kill Kill Kill','Kill The Noise','She Likes To Party');
INSERT INTO MUSIC VALUES (358,'Kill Kill Kill','Kill The Noise','Kill The Noise (Dillon Francis Remix)');
INSERT INTO MUSIC VALUES (359,'Kings Of Crunk','Lil JonYing Yang Twins','Get Low');
INSERT INTO MUSIC VALUES (360,'Korn feat. Skrillex - Narcissistic Cannibal (Vocal Version)','Ultimate Tribute Stars','Korn feat. Skrillex - Narcissistic Cannibal (Vocal Version)');
INSERT INTO MUSIC VALUES (361,'La La La (feat. Sam Smith)','Naughty BoySam Smith','La La La - feat. Sam Smith');
INSERT INTO MUSIC VALUES (362,'La Suite','1995','La Suite');
INSERT INTO MUSIC VALUES (363,'Labyrinth Remix Project','Kraddy','Minotaur - DLX RMX');
INSERT INTO MUSIC VALUES (364,'Labyrinth Remix Project','Kraddy','Let Go - Instrumental Version');
INSERT INTO MUSIC VALUES (365,'Lambs Anger','Mr Oizo','Positif');
INSERT INTO MUSIC VALUES (366,'Laptop Symphony','Midnight ConspiracyCenob1te','The Eye');
INSERT INTO MUSIC VALUES (367,'Laptop Symphony','Cosmic GateJesKillbot','Flying Blind (Killbot War Paint Mashup Mix)');
INSERT INTO MUSIC VALUES (368,'Lassitude','DJ Fresh','Talkbox - Camo & Krooked Remix');
INSERT INTO MUSIC VALUES (369,'The Last Resort','Trentemøller','Take Me Into Your Skin - Original Mix');
INSERT INTO MUSIC VALUES (370,'Last Train to Paradise - Single','Kdrew','Last Train to Paradise - Original');
INSERT INTO MUSIC VALUES (371,'The Lateness Of The Hour','Alex Clare','Too Close');
INSERT INTO MUSIC VALUES (372,'Lead Sails Paper Anchor','Atreyu','Blow');
INSERT INTO MUSIC VALUES (373,'The Legend Of Zelda','Zedd','The Legend Of Zelda - Original Mix');
INSERT INTO MUSIC VALUES (374,'The Legend Of Zelda','Zedd','The Legend Of Zelda - Electrixx Remix');
INSERT INTO MUSIC VALUES (375,'Lest We Forget (The Best Of)','Marilyn Manson','Personal Jesus');
INSERT INTO MUSIC VALUES (376,'Let Go With You (Remixes)','Josh Money','Let Go With You - Drivepilot Remix');
INSERT INTO MUSIC VALUES (377,'Let it Go','Dragonette','Let it Go');
INSERT INTO MUSIC VALUES (378,'Let It Rock','Kevin RudolfLil Wayne','Let It Rock');
INSERT INTO MUSIC VALUES (379,'Let Me Go Remixes','Filth CollinsAaA','Get Out - AaA Remix');
INSERT INTO MUSIC VALUES (380,'Lets RAGE','Nerd Rage','Lets RAGE');
INSERT INTO MUSIC VALUES (381,'Lies','Hyper','Clockwork - Original Mix');
INSERT INTO MUSIC VALUES (382,'Life Starts Now','Three Days Grace','Bitter Taste');
INSERT INTO MUSIC VALUES (383,'Life Starts Now','Three Days Grace','Break');
INSERT INTO MUSIC VALUES (384,'Life Starts Now','Three Days Grace','The Good Life');
INSERT INTO MUSIC VALUES (385,'Life Starts Now','Three Days Grace','Someone Who Cares');
INSERT INTO MUSIC VALUES (386,'Life Starts Now','Three Days Grace','Goin'' Down');
INSERT INTO MUSIC VALUES (387,'Lights Out EP','Marcus Schössow','I <3 You - Original Mix');
INSERT INTO MUSIC VALUES (388,'Lightspeed','Kill The Noise & Datsik','Lightspeed');
INSERT INTO MUSIC VALUES (389,'Like a Boss EP','Eptic','Oh Snap!');
INSERT INTO MUSIC VALUES (390,'Like Boom','Nick Thayer','Facepalm');
INSERT INTO MUSIC VALUES (391,'Lindsey Stirling','Lindsey Stirling','Electric Daisy Violin');
INSERT INTO MUSIC VALUES (392,'Lindsey Stirling','Lindsey Stirling','Crystallize');
INSERT INTO MUSIC VALUES (393,'Lindsey Stirling','Lindsey Stirling','Moon Trance');
INSERT INTO MUSIC VALUES (394,'Lindsey Stirling','Lindsey Stirling','Elements');
INSERT INTO MUSIC VALUES (395,'Lindsey Stirling','Lindsey Stirling','Shadows');
INSERT INTO MUSIC VALUES (396,'Lindsey Stirling','Lindsey Stirling','Spontaneous Me');
INSERT INTO MUSIC VALUES (397,'Lines In Wax EP','Flux Pavilion','Hold Me Close');
INSERT INTO MUSIC VALUES (398,'Lines In Wax EP','Flux Pavilion','I Can''t Stop');
INSERT INTO MUSIC VALUES (399,'Lines In Wax EP','Flux Pavilion','Haunt You');
INSERT INTO MUSIC VALUES (400,'The Living Dead EP','Zeds DeadOmar LinX','Cowboy');
INSERT INTO MUSIC VALUES (401,'Loose Dirt','Klaypex','Lights');
INSERT INTO MUSIC VALUES (402,'Loose Dirt','Klaypex','Gamefire (feat. Mike Diva)');
INSERT INTO MUSIC VALUES (403,'Loose Dirt','Klaypex','Hey Hey');
INSERT INTO MUSIC VALUES (404,'Loose Dirt','Klaypex','DUBSTEP GUNS (Bonus Track)');
INSERT INTO MUSIC VALUES (405,'Lost & Found','Afrojack','Daft Sound - Original Mix');
INSERT INTO MUSIC VALUES (406,'Lost & Found: Limp Bizkit','Limp Bizkit','Rollin'' (Air Raid Vehicle)');
INSERT INTO MUSIC VALUES (407,'The Lost Tracks','Pegboard Nerds','FrainBreeze');
INSERT INTO MUSIC VALUES (408,'The Lost Tracks','Pegboard Nerds','Close Encounter');
INSERT INTO MUSIC VALUES (409,'The Lost Tracks','Pegboard Nerds','20K');
INSERT INTO MUSIC VALUES (410,'The Lost Tracks','Pegboard Nerds','Lawless');
INSERT INTO MUSIC VALUES (411,'The Lost Tracks','Pegboard Nerds','Rocktronik');
INSERT INTO MUSIC VALUES (412,'LP4','Ratatat','Bilar');
INSERT INTO MUSIC VALUES (413,'LP4','Ratatat','Drugs');
INSERT INTO MUSIC VALUES (414,'LP4','Ratatat','Neckbrace');
INSERT INTO MUSIC VALUES (415,'LP4','Ratatat','We Can’t Be Stopped');
INSERT INTO MUSIC VALUES (416,'LP4','Ratatat','Bob Gandhi');
INSERT INTO MUSIC VALUES (417,'LP4','Ratatat','Mandy');
INSERT INTO MUSIC VALUES (418,'LP4','Ratatat','Party With Children');
INSERT INTO MUSIC VALUES (419,'LP4','Ratatat','Sunblocks');
INSERT INTO MUSIC VALUES (420,'LP4','Ratatat','Grape Juice City');
INSERT INTO MUSIC VALUES (421,'Lucky Shiner','Gold Panda','Marriage');
INSERT INTO MUSIC VALUES (422,'Lunar EP','Rudebrat','Eastern Riot - Original Mix');
INSERT INTO MUSIC VALUES (423,'Mad Decent Volume 1','BlaqstarrDiplo','Get Off - (Jack Beats Remix)');
INSERT INTO MUSIC VALUES (424,'Mad Liberation','Griz','Blastaa');
INSERT INTO MUSIC VALUES (425,'Mad Liberation','GrizDominic Lalli','Mr. B (feat. Dominic Lalli)');
INSERT INTO MUSIC VALUES (426,'Mad Liberation','Griz','Better Than I''ve Ever Been');
INSERT INTO MUSIC VALUES (427,'Mad Liberation','Griz','The Future Is Now');
INSERT INTO MUSIC VALUES (428,'Mad World / Mario Is It You?','DeadWish','Mad World - Original Mix');
INSERT INTO MUSIC VALUES (429,'Magnetic Man','Magnetic Man ft Katy B','Crossover');
INSERT INTO MUSIC VALUES (430,'Make It Bun Dem','SkrillexDamian Marley','Make It Bun Dem');
INSERT INTO MUSIC VALUES (431,'Make The Floor Shake','Rudebrat','Make The Floor Shake - Original Mix');
INSERT INTO MUSIC VALUES (432,'Make The Floor Shake','RudebratBassex','Changing The Game - Bassex Remix');
INSERT INTO MUSIC VALUES (433,'Making Mirrors','GotyeKimbra','Somebody That I Used To Know');
INSERT INTO MUSIC VALUES (434,'Making Monsters','Combichrist','Never Surrender');
INSERT INTO MUSIC VALUES (435,'Manual for successful rioting','Birdy Nam Nam','The Parachute Ending');
INSERT INTO MUSIC VALUES (436,'Massive Hits! - Nineties','Placebo','Pure Morning - Radio Edit; 2004 Remastered Version');
INSERT INTO MUSIC VALUES (437,'The Matrix Reloaded: The Album','Marilyn Manson','This Is The New Shit');
INSERT INTO MUSIC VALUES (438,'The Matrix Reloaded: The Album','Rob Dougan','Chateau');
INSERT INTO MUSIC VALUES (439,'Max Out EP','Koan Sound','Mr. Brown');
INSERT INTO MUSIC VALUES (440,'Mechanical Animals','Marilyn Manson','Rock Is Dead');
INSERT INTO MUSIC VALUES (441,'Mechanical Remixes','OliverNom De Strip','Control - Nom De Strip Remix');
INSERT INTO MUSIC VALUES (442,'Megalithic Symphony','AWOLNATION','Sail');
INSERT INTO MUSIC VALUES (443,'Meow Meow','High Rankin','Meow Meow');
INSERT INTO MUSIC VALUES (444,'Mezmerize','System Of A Down','Violent Pornography - Explicit Album Version');
INSERT INTO MUSIC VALUES (445,'Minerals','CongorockNom De Strip','Minerals');
INSERT INTO MUSIC VALUES (446,'Mixmag Mix – ‘Clever Title Like Deadmau5 Would Use’ Mix','Knife Party','Mixmag Mix – ‘Clever Title Like Deadmau5 Would Use’ Mix');
INSERT INTO MUSIC VALUES (447,'Mole Listening Pearls - The Collection Vol. 3 (2006 - 2009)','Wax Tailor','Que Sera');
INSERT INTO MUSIC VALUES (448,'Molly','TygaCedric GervaisWiz KhalifaMally Mall','Molly');
INSERT INTO MUSIC VALUES (449,'The Monsoon E.p.','Mizuki''s Last Chance','Watashi Wa Mizuki Desu - (VIP)');
INSERT INTO MUSIC VALUES (450,'MONSTA EP','Monsta','Where Did I Go? - Dillon Francis & Kill Paris Remix');
INSERT INTO MUSIC VALUES (451,'Monster EP','Ikya','Monster');
INSERT INTO MUSIC VALUES (452,'Monstercat - Best of 2011','Noisestorm','Backlash');
INSERT INTO MUSIC VALUES (453,'Monstercat 001 - Launch Week','Arion','Cold Blood & Ice Cream Cones');
INSERT INTO MUSIC VALUES (454,'Monstercat 001 - Launch Week','Going Quantum','Hello?');
INSERT INTO MUSIC VALUES (455,'Monstercat 001 - Launch Week','Neilio','Captivating');
INSERT INTO MUSIC VALUES (456,'Monstercat 003 - Momentum','Stephen Walking','Top of the World');
INSERT INTO MUSIC VALUES (457,'Monstercat 004 - Identity','Rezonate','Pump It!');
INSERT INTO MUSIC VALUES (458,'Monstercat 005 - Evolution','Krewella','Killin It');
INSERT INTO MUSIC VALUES (459,'Monstercat 005 - Evolution','Obsidia','Illusion');
INSERT INTO MUSIC VALUES (460,'Monstercat 006 - Embrace','Monstercat','Monstercat 006 - Embrace Album Mix');
INSERT INTO MUSIC VALUES (461,'Monstercat 007 - Solace','Tristam','I Remember');
INSERT INTO MUSIC VALUES (462,'Monstercat 007 - Solace','Monstercat','Solace Album Mix');
INSERT INTO MUSIC VALUES (463,'Monstercat 008 - Anniversary','Pegboard Nerds','Pressure Cooker');
INSERT INTO MUSIC VALUES (464,'Monstercat 009 - Reunion','Pegboard Nerds','Fire in the Hole');
INSERT INTO MUSIC VALUES (465,'Monstercat 009 - Reunion','Krewella','One Minute (DotEXE''s Dopest Dope Remix)');
INSERT INTO MUSIC VALUES (466,'Monstercat 013 - Awakening','VarienRazihel','Toothless Hawkins (And His Robot Jazz Band)');
INSERT INTO MUSIC VALUES (467,'Monsters of Drumstep Vol 2','Figure','Werewolf - VIP Edit');
INSERT INTO MUSIC VALUES (468,'Mordez Moi / B.R.U.L.','Feed Me','Mordez Moi');
INSERT INTO MUSIC VALUES (469,'More Heroes','Quartus SaulTim Ismag','Los Angeles - Tim Ismag Remix');
INSERT INTO MUSIC VALUES (470,'More Heroes','Quartus SaulTwist (UK)Maksim','Superheroes - Twist Remix');
INSERT INTO MUSIC VALUES (471,'More Monsters and Sprites EP','Skrillex','First Of The Year - Equinox');
INSERT INTO MUSIC VALUES (472,'Mortal Kombat: Songs Inspired By The Warriors','Skrillex','Reptile''s Theme');
INSERT INTO MUSIC VALUES (473,'Mr Mongoose''s Fantastic Weekend EP','Doctor PDillon FrancisVarious Artists','Music Is Dead');
INSERT INTO MUSIC VALUES (474,'Music From And Inspired By The Motion Picture The Matrix','Rob Dougan','Clubbed To Death - Kurayamino Variation');
INSERT INTO MUSIC VALUES (475,'Music From The Motion Picture Not Another Teen Movie','Marilyn Manson','Tainted Love');
INSERT INTO MUSIC VALUES (476,'Nanoo EP1','Nanoo','Lighted Up - Original Mix');
INSERT INTO MUSIC VALUES (477,'Neo Eden EP','Meta','Atom and Eve');
INSERT INTO MUSIC VALUES (478,'Neo Eden EP','Meta','Reign');
INSERT INTO MUSIC VALUES (479,'Neo Eden EP','Meta','The Wolf');
INSERT INTO MUSIC VALUES (480,'New Soul','Yael Naim','New Soul');
INSERT INTO MUSIC VALUES (481,'Next Order / Middle Finger','Dog Blood','Next Order');
INSERT INTO MUSIC VALUES (482,'Nightcall','Kavinsky','Nightcall');
INSERT INTO MUSIC VALUES (483,'Nightfall','Tony Anthem and Axl Ender','Nightfall');
INSERT INTO MUSIC VALUES (484,'Nightmare Revisited','Marilyn Manson','This Is Halloween');
INSERT INTO MUSIC VALUES (485,'Nights in Bangalore','VarienDirt Monkey','Nights in Bangalore - Dirt Monkey Remix');
INSERT INTO MUSIC VALUES (486,'NineSevenTwo EP','Whisker Twister','Fucking Cunt');
INSERT INTO MUSIC VALUES (487,'Ninur','Savant','You Can Play - Original Mix');
INSERT INTO MUSIC VALUES (488,'Ninur','Savant','The Third Eye - Original Mix');
INSERT INTO MUSIC VALUES (489,'No Requests EP','Hot Mess','No Requests - Original Mix');
INSERT INTO MUSIC VALUES (490,'No Stopping Us (feat. Foreign Beggars) [Remixes]','DirtyphonicsForeign Beggars','No Stopping Us (feat. Foreign Beggars) - Steve Aoki Remix');
INSERT INTO MUSIC VALUES (491,'No, Not Me, Never','Photo Atlas','Red Orange Yellow');
INSERT INTO MUSIC VALUES (492,'Not Accepted Anywhere','The Automatic','Monster');
INSERT INTO MUSIC VALUES (493,'Nothing But The Beat','David Guetta','Metro Music');
INSERT INTO MUSIC VALUES (494,'Nothing But The Beat','David Guetta','Toy Story');
INSERT INTO MUSIC VALUES (495,'Nothing But The Beat','David Guetta','Glasgow');
INSERT INTO MUSIC VALUES (496,'Nuclear Blast','Noizer','Nuclear Blast - Original Mix');
INSERT INTO MUSIC VALUES (497,'Off The Grid EP','Dubscribe','Off The Grid - Original Mix');
INSERT INTO MUSIC VALUES (498,'OK Cowboy','Vitalic','La Rock 01');
INSERT INTO MUSIC VALUES (499,'One Day / Reckoning Song (Wankelmut Remix)','The Mojos','One Day / Reckoning Song (Wankelmut Remix) - Radio Edit');
INSERT INTO MUSIC VALUES (500,'One Two Remixes','KezwikKairo Kingdom','One Two - Kezwik Remix');
INSERT INTO MUSIC VALUES (501,'One-X','Three Days Grace','Let it Die');
INSERT INTO MUSIC VALUES (502,'One-X','Three Days Grace','Time of Dying');
INSERT INTO MUSIC VALUES (503,'One-X','Three Days Grace','Gone Forever');
INSERT INTO MUSIC VALUES (504,'One-X','Three Days Grace','Pain');
INSERT INTO MUSIC VALUES (505,'One-X','Three Days Grace','Animal I Have Become');
INSERT INTO MUSIC VALUES (506,'One-X','Three Days Grace','Never Too Late');
INSERT INTO MUSIC VALUES (507,'Onslaught','Cenob1te','Onslaught');
INSERT INTO MUSIC VALUES (508,'Oracular Spectacular','MGMT','Kids');
INSERT INTO MUSIC VALUES (509,'Orelsan et Gringe sont les Casseurs Flowters','Casseurs Flowters','15h02 - Regarde comme il fait beau (dehors)');
INSERT INTO MUSIC VALUES (510,'Original Musiquarium','Stevie Wonder','I Wish');
INSERT INTO MUSIC VALUES (511,'Orion','she','Escape');
INSERT INTO MUSIC VALUES (512,'Orion','she','Atomic');
INSERT INTO MUSIC VALUES (513,'Orion','she','Just Your Eyes');
INSERT INTO MUSIC VALUES (514,'Over It / Don''t Stop','At Dawn We Rage','Over It - Original Mix');
INSERT INTO MUSIC VALUES (515,'Overworld','Savant','Ride Like The Wind - Original Mix');
INSERT INTO MUSIC VALUES (516,'Overworld','Savant','Flashbach - Original Mix');
INSERT INTO MUSIC VALUES (517,'Panther Remixes + Hot Contact','Barletta','Panther - Zeds Dead SalaciousSound Remix');
INSERT INTO MUSIC VALUES (518,'Past, Present & Future','Rob Zombie','Dragula');
INSERT INTO MUSIC VALUES (519,'The Past,The Present & The Future','Dirtyphonics','Vandals');
INSERT INTO MUSIC VALUES (520,'The Path Of Totality (Special Edition)','Korn','Narcissistic Cannibal - feat. Skrillex & Kill The Noise');
INSERT INTO MUSIC VALUES (521,'The Path Of Totality (Special Edition)','Korn','Get Up! - feat. Skrillex');
INSERT INTO MUSIC VALUES (522,'Pedro The Destroyer','Nit Grit','Hyphycide');
INSERT INTO MUSIC VALUES (523,'Perfect Day / Shake N Bake','Notixx','Shake N Bake - Original Mix');
INSERT INTO MUSIC VALUES (524,'Ping Pong','Armin van Buuren','Ping Pong - Radio Edit');
INSERT INTO MUSIC VALUES (525,'Ping Pong EP','Bassnectar','Ping Pong');
INSERT INTO MUSIC VALUES (526,'A Place Where The Sun Is Silent (Deluxe Edition)','Alesana','A Gilded Masquerade (score)');
INSERT INTO MUSIC VALUES (527,'Play For Real (featuring The Heavy)','The Crystal Method','Play For Real (feat. The Heavy) - Dirtyphonics Remix');
INSERT INTO MUSIC VALUES (528,'Play Hard EP','Krewella','One Minute');
INSERT INTO MUSIC VALUES (529,'Playing In The Shadows','Example','Midnight Run');
INSERT INTO MUSIC VALUES (530,'Playlist: The Very Best Of Korn','Korn','Freak on a Leash');
INSERT INTO MUSIC VALUES (531,'Playlist: The Very Best Of RUN-DMC','RUN-DMC','It''s Tricky');
INSERT INTO MUSIC VALUES (532,'Please Hammer Don''t Hurt ''Em','MC Hammer','U Can''t Touch This');
INSERT INTO MUSIC VALUES (533,'Polarize EP (feat. Shaz Sparks)','Seven LionsShaz Sparks','Polarized');
INSERT INTO MUSIC VALUES (534,'PowerBallin''','Chingy','I Do');
INSERT INTO MUSIC VALUES (535,'Pretty Hate Machine: 2010 Remaster','Nine Inch Nails','Head Like A Hole - Remastered');
INSERT INTO MUSIC VALUES (536,'Proxy','Martin Garrix','Proxy - Original Mix');
INSERT INTO MUSIC VALUES (537,'Punk Goes Pop Volume Two','Alesana','What Goes Around... (Justin Timberlake cover)');
INSERT INTO MUSIC VALUES (538,'Purple','MartyParty','Eggs and Toast');
INSERT INTO MUSIC VALUES (539,'Pursuit','Gesaffelstein','Pursuit');
INSERT INTO MUSIC VALUES (540,'Rack City','Tyga','Rack City');
INSERT INTO MUSIC VALUES (541,'Rage Against The Machine - XX (20th Anniversary Special Edition)','Rage Against The Machine','Bombtrack - Remastered');
INSERT INTO MUSIC VALUES (542,'Rage Against The Machine - XX (20th Anniversary Special Edition)','Rage Against The Machine','Killing In The Name - Remastered');
INSERT INTO MUSIC VALUES (543,'Rage Against The Machine - XX (20th Anniversary Special Edition)','Rage Against The Machine','Know Your Enemy - Remastered');
INSERT INTO MUSIC VALUES (544,'Rage Valley EP','Knife Party','Centipede');
INSERT INTO MUSIC VALUES (545,'Raise Your Hands','Ummet Ozcan','Raise Your Hands - Original Mix');
INSERT INTO MUSIC VALUES (546,'Ratatat','Ratatat','Breaking Away');
INSERT INTO MUSIC VALUES (547,'Rave Age','Vitalic','Stamina');
INSERT INTO MUSIC VALUES (548,'Ready to Go','Klaypex','Manners');
INSERT INTO MUSIC VALUES (549,'Ready to Go','Klaypex','Petrified');
INSERT INTO MUSIC VALUES (550,'Ready to Go','Klaypex','Too Late');
INSERT INTO MUSIC VALUES (551,'Ready to Go','Klaypex','Stars (feat. Sara Kay)');
INSERT INTO MUSIC VALUES (552,'Ready To Stomp EP','Far Too Loud','Moneymaker');
INSERT INTO MUSIC VALUES (553,'The Reason','Hoobastank','Out Of Control');
INSERT INTO MUSIC VALUES (554,'The Reason','Hoobastank','The Reason');
INSERT INTO MUSIC VALUES (555,'Rebel Era','Griz','Crime in the City');
INSERT INTO MUSIC VALUES (556,'Rebel Era','Griz','Gettin'' Live');
INSERT INTO MUSIC VALUES (557,'Rebel Era','Griz','Dance With Me');
INSERT INTO MUSIC VALUES (558,'Rebel Era','Griz','Too Young for Tragedy Pt. II');
INSERT INTO MUSIC VALUES (559,'Recess','Skrillex','Recess');
INSERT INTO MUSIC VALUES (560,'Recess','Skrillex','Ragga Bomb');
INSERT INTO MUSIC VALUES (561,'Recess','Skrillex','Fuck That');
INSERT INTO MUSIC VALUES (562,'RECHARGED','Linkin Park','LOST IN THE ECHO - KillSonik Remix');
INSERT INTO MUSIC VALUES (563,'Reconstrukted Remix EP','Calvertron','8 Bit Dreamz ft. Melleefresh (Calvertron VIP Mix)');
INSERT INTO MUSIC VALUES (564,'Red Heat','Skism','Red Heat');
INSERT INTO MUSIC VALUES (565,'Redefine EP','Soil','Pride');
INSERT INTO MUSIC VALUES (566,'The Remixes','FreestylersPendulum','Pain Killer - Kouncilhouse Remix');
INSERT INTO MUSIC VALUES (567,'Renegade','The QemistsMaxsta','Renegade - The Qemists VIP');
INSERT INTO MUSIC VALUES (568,'Renegade EP','Noisestorm','Let It Roar');
INSERT INTO MUSIC VALUES (569,'The Resistance','Muse','Uprising');
INSERT INTO MUSIC VALUES (570,'Retro City','Adventure Club','Retro City');
INSERT INTO MUSIC VALUES (571,'Revelations','Audioslave','Broken City');
INSERT INTO MUSIC VALUES (572,'Revelations','Audioslave','Revelations');
INSERT INTO MUSIC VALUES (573,'Riding High - EP','Destroy Disco','Riding High - Dodge & Fuski Remix');
INSERT INTO MUSIC VALUES (574,'Rocksteady','The Bloody Beetroots','Rocksteady');
INSERT INTO MUSIC VALUES (575,'Romborama','The Bloody Beetroots','Warp 1.9 (feat. Steve Aoki)');
INSERT INTO MUSIC VALUES (576,'Rudeboy','Zeds Dead','Rude Boy');
INSERT INTO MUSIC VALUES (577,'Runnin''','CutlineBelle Humble','Runnin'' - VIP Mix');
INSERT INTO MUSIC VALUES (578,'Salt For Your Wounds','timebomb','Twisted & Evil - Original Mix');
INSERT INTO MUSIC VALUES (579,'Sauce Boss (feat. Epic Meal Time)','Klaypex','Sauce Boss (feat. Epic Meal Time)');
INSERT INTO MUSIC VALUES (580,'Save The World (The Remixes)','Swedish House Mafia','Save the World - Knife Party Remix');
INSERT INTO MUSIC VALUES (581,'Say My Name','Porter Robinson','Say My Name (Radio Edit)');
INSERT INTO MUSIC VALUES (582,'SBTRKT','SBTRKT','Wildfire (feat. Little Dragon)');
INSERT INTO MUSIC VALUES (583,'Scary Monsters and Nice Sprites (Deluxe Tour Edition)','Skrillex','Scary Monsters And Nice Sprites');
INSERT INTO MUSIC VALUES (584,'Scary Monsters and Nice Sprites (Deluxe Tour Edition)','Skrillex','Kill EVERYBODY');
INSERT INTO MUSIC VALUES (585,'Scary Monsters and Nice Sprites (Deluxe Tour Edition)','Skrillex','Scatta - feat. Foreign Beggars & Bare Noize');
INSERT INTO MUSIC VALUES (586,'Scary Monsters and Nice Sprites (Deluxe Tour Edition)','Skrillex','Scary Monsters And Nice Sprites - Noisa Remix');
INSERT INTO MUSIC VALUES (587,'The Science Project','Schoolboy','Zombies Ate My Neighbours');
INSERT INTO MUSIC VALUES (588,'The Scientific Method, Vol 2','Professor Kliq','Plastic and Flashing Lights');
INSERT INTO MUSIC VALUES (589,'The Scientific Method, Vol 2','Professor Kliq','Pangea');
INSERT INTO MUSIC VALUES (590,'Seether: 2002 - 2013','Seether','Breakdown');
INSERT INTO MUSIC VALUES (591,'#SELFIE','The Chainsmokers','#SELFIE');
INSERT INTO MUSIC VALUES (592,'Send Me Your Love (KDrew Remix) - Single','Taryn Manning','Send Me Your Love - KDrew Remix');
INSERT INTO MUSIC VALUES (593,'Seven Stitches / Groundhog','Noisia','Seven Stitches');
INSERT INTO MUSIC VALUES (594,'Seven Stitches / Groundhog','Noisia','Groundhog');
INSERT INTO MUSIC VALUES (595,'The Seventh Passenger','Sietta','What Am I Supposed To Do?');
INSERT INTO MUSIC VALUES (596,'Shadow Puppets Remixes','NovaSyrebral','Shadow Puppets - Syrebral Remix');
INSERT INTO MUSIC VALUES (597,'Shave It - The Aftershave','Zedd','Shave It (501 Remix)');
INSERT INTO MUSIC VALUES (598,'The Sickness 10th Anniversary Edition','Disturbed','Down With The Sickness');
INSERT INTO MUSIC VALUES (599,'Sierra Leone (Remixes)','Mt. EdenFreshlyground','Sierra Leone');
INSERT INTO MUSIC VALUES (600,'Signs of a Struggle','Mattafix','Big City Life');
INSERT INTO MUSIC VALUES (601,'Sinner','Drowning Pool','Bodies');
INSERT INTO MUSIC VALUES (602,'Sithstep','Earthworm Joe','Sithstep - Original Mix');
INSERT INTO MUSIC VALUES (603,'Sky Child EP','MUST DIE!Natasha Fox','I''m So Sorry');
INSERT INTO MUSIC VALUES (604,'Slam the Door','Zedd','Slam the Door');
INSERT INTO MUSIC VALUES (605,'Slime City / Trouble','Eptic','Slime City');
INSERT INTO MUSIC VALUES (606,'Slurp And Giggle','Opiuo','Creamy Taco');
INSERT INTO MUSIC VALUES (607,'Smashing Newbs','Tristam','You Clearly Let It Show');
INSERT INTO MUSIC VALUES (608,'Smells Like Children','Marilyn Manson','Sweet Dreams (Are Made Of This)');
INSERT INTO MUSIC VALUES (609,'Some Nights','Fun.Janelle Monáe','We Are Young (feat. Janelle Monáe) - feat. Janelle Monae');
INSERT INTO MUSIC VALUES (610,'Some Wobbles - EP','Ephixa','Some Wobbles');
INSERT INTO MUSIC VALUES (611,'Songs','Rusko','Somebody To Love');
INSERT INTO MUSIC VALUES (612,'Songs About Jane','Maroon 5','This Love');
INSERT INTO MUSIC VALUES (613,'Sonic Manipulator','Document One','DOCUMENT ONE - SONIC MANIPULATOR');
INSERT INTO MUSIC VALUES (614,'Sound Surgery EP','Killbot','I''ll Fuck It');
INSERT INTO MUSIC VALUES (615,'Soundsystem','The Qemists','Be Electric');
INSERT INTO MUSIC VALUES (616,'Soundtrack For The Voices In My Head Vol. 02','Celldweller','Senorita Bonita');
INSERT INTO MUSIC VALUES (617,'Soundtrack for the Voices in My Head Vol. 02','Celldweller','Pulsar');
INSERT INTO MUSIC VALUES (618,'Space 21 EP','Brownz','Space 21');
INSERT INTO MUSIC VALUES (619,'Spitfire','Porter Robinson','Spitfire');
INSERT INTO MUSIC VALUES (620,'Spitfire','Porter Robinson','Unison');
INSERT INTO MUSIC VALUES (621,'Spitfire','Porter Robinson','Unison - Knife Party Remix');
INSERT INTO MUSIC VALUES (622,'St. Elsewhere','Gnarls Barkley','Crazy');
INSERT INTO MUSIC VALUES (623,'Stabs EP','xKore','Everybody Rock');
INSERT INTO MUSIC VALUES (624,'Stadium Arcadium','Red Hot Chili Peppers','Dani California');
INSERT INTO MUSIC VALUES (625,'Steal This Album!','System Of A Down','Innervision');
INSERT INTO MUSIC VALUES (626,'Steal This Album!','System Of A Down','Bubbles');
INSERT INTO MUSIC VALUES (627,'Steal This Album!','System Of A Down','Boom!');
INSERT INTO MUSIC VALUES (628,'Step Back (Radio Edit) [feat. Kris Kiss]','Chocolate PumaKris Kiss','Step Back (Radio Edit) [feat. Kris Kiss]');
INSERT INTO MUSIC VALUES (629,'Stop The Rock','Apollo 440','Stop the Rock - Apollo 440 Original Mix');
INSERT INTO MUSIC VALUES (630,'Straight Up Dubstep!','Arkasia','New World Disorder - Original Mix');
INSERT INTO MUSIC VALUES (631,'Straight Up Dubstep! Vol. 4','MitisShift FourDavid ReedDirtyrock','Take It Out On Me - MitiS Remix');
INSERT INTO MUSIC VALUES (632,'Street Bangerz Volume 3 & 4','Gramatik','Dungeon Sound');
INSERT INTO MUSIC VALUES (633,'The Studio Album Collection','Disturbed','Stupify');
INSERT INTO MUSIC VALUES (634,'Sub ON','MartyParty','Ice Cream Truck');
INSERT INTO MUSIC VALUES (635,'Substance D Remixes','DieselboyDemo','OD - Gein + Counterstrike Remix');
INSERT INTO MUSIC VALUES (636,'Super Hexagon','Chipzel','Courtesy');
INSERT INTO MUSIC VALUES (637,'Super Meat Boy! - Official Special Edition Soundtrack','Danny Baranowsky','Forest Funk (Ch 1 Light World)');
INSERT INTO MUSIC VALUES (638,'SuperBestFriends','Popeska','SuperBestFriends');
INSERT INTO MUSIC VALUES (639,'Superhero','Rabbit KillerFarleon','Superhero (Original Mix)');
INSERT INTO MUSIC VALUES (640,'Superhuman','Virtual RiotAmba Shepherd','Superhuman - Club Mix');
INSERT INTO MUSIC VALUES (641,'Superman','Mojo','The Future');
INSERT INTO MUSIC VALUES (642,'Supermassive Black Hole','Muse','Supermassive Black Hole');
INSERT INTO MUSIC VALUES (643,'Supertrail','Savoy','Devil''s On Horseback');
INSERT INTO MUSIC VALUES (644,'Sushi Of God','Nom De StripNEZZO','Sushi Of God - Original Mix');
INSERT INTO MUSIC VALUES (645,'Swagga / Invaderz','Excision and Datsik','Swagga');
INSERT INTO MUSIC VALUES (646,'Sweet Shop (Flux Pavilion Remix)','Doctor P','Sweet Shop (Flux Pavilion Remix)');
INSERT INTO MUSIC VALUES (647,'Sweet Shop / Gargoyle','Doctor P','Sweet Shop');
INSERT INTO MUSIC VALUES (648,'Sweet Talk EP','KitoReija Lee','Sweet Talk');
INSERT INTO MUSIC VALUES (649,'Swim','Caribou','Odessa');
INSERT INTO MUSIC VALUES (650,'TAKE & FAKE','Grim','Pikachu - Original Mix');
INSERT INTO MUSIC VALUES (651,'Talk Dirty (feat. 2 Chainz)','Jason Derulo2 Chainz','Talk Dirty (feat. 2 Chainz)');
INSERT INTO MUSIC VALUES (652,'The Tarantino EP','Dirtyphonics','Tarantino');
INSERT INTO MUSIC VALUES (653,'Telescopic','Supervision','Giving Me Life');
INSERT INTO MUSIC VALUES (654,'Terminal Static','Broken Note','Mask Of Gas');
INSERT INTO MUSIC VALUES (655,'Tetra','C2CPigeon John','Because Of You');
INSERT INTO MUSIC VALUES (656,'Tetra','C2C','Delta');
INSERT INTO MUSIC VALUES (657,'Texicali','ZZ Top','Chartreuse');
INSERT INTO MUSIC VALUES (658,'Their Law The Singles 1990 - 2005','The Prodigy','Voodoo People (Pendulum Mix)');
INSERT INTO MUSIC VALUES (659,'This Is Music: The Singles 92-98','The Verve','Bitter Sweet Symphony - 2004 Digital Remaster');
INSERT INTO MUSIC VALUES (660,'This Isn''t House EP','Dream','This Isn''t House - Flinch Remix');
INSERT INTO MUSIC VALUES (661,'A Thousand Suns','Linkin Park','Blackout');
INSERT INTO MUSIC VALUES (662,'A Thousand Suns','Linkin Park','Wretches And Kings');
INSERT INTO MUSIC VALUES (663,'Three Days Grace (Deluxe Version)','Three Days Grace','I Hate Everything About You');
INSERT INTO MUSIC VALUES (664,'Thrift Shop (feat. Wanz)','Macklemore & Ryan Lewis','Thrift Shop - feat. Wanz');
INSERT INTO MUSIC VALUES (665,'Time to Slam','Tomba','Kneeyan');
INSERT INTO MUSIC VALUES (666,'Timestretch','Bassnectar','Here We Go');
INSERT INTO MUSIC VALUES (667,'Timestretch','Bassnectar','Timestretch');
INSERT INTO MUSIC VALUES (668,'To A New Earth EP','Kill Paris','Catch You');
INSERT INTO MUSIC VALUES (669,'To Be Loved: The Best Of Papa Roach','Papa Roach','Last Resort');
INSERT INTO MUSIC VALUES (670,'To Be Loved: The Best Of Papa Roach','Papa Roach','Getting Away With Murder');
INSERT INTO MUSIC VALUES (671,'To The Stars','Feed MeTasha Baxter','Strange Behaviour - Original Mix');
INSERT INTO MUSIC VALUES (672,'Tommy''s Theme','Noisia','Tommy''s Theme - Original Mix');
INSERT INTO MUSIC VALUES (673,'Tornado (Remixes)','TiëstoSteve AokiPolina','Tornado (Kill the Noise Remix feat. Polina)');
INSERT INTO MUSIC VALUES (674,'Touch Sound EP','Xilent','Touch Sound');
INSERT INTO MUSIC VALUES (675,'Toxicity','System Of A Down','Chop Suey!');
INSERT INTO MUSIC VALUES (676,'Toxicity','System Of A Down','Toxicity');
INSERT INTO MUSIC VALUES (677,'Tremor (Sensation 2014 Anthem)','Dimitri VegasMartin GarrixLike Mike','Tremor (Sensation 2014 Anthem)');
INSERT INTO MUSIC VALUES (678,'True','Avicii','Wake Me Up');
INSERT INTO MUSIC VALUES (679,'True','Avicii','Hey Brother');
INSERT INTO MUSIC VALUES (680,'Try It Out','SkrillexAlvin Risk','Try It Out - Neon Mix');
INSERT INTO MUSIC VALUES (681,'Turn Down for What','DJ SnakeLil Jon','Turn Down for What');
INSERT INTO MUSIC VALUES (682,'Turn On The Bright Lights','Interpol','Obstacle 1');
INSERT INTO MUSIC VALUES (683,'U Dun Know Dubstep 2','WideboysMcLeanSway','Shopaholic - Funtcase Club Mix');
INSERT INTO MUSIC VALUES (684,'UKF Dubstep 2011','Dubba Jonny','Not Another UKF Dubstep Tutorial');
INSERT INTO MUSIC VALUES (685,'UKF Dubstep 2011','RackNRuin feat. Janai & IllamanRackNRuinJanaiIllaman','Dazed & Confused - SKisM''s Baroque Out Remix');
INSERT INTO MUSIC VALUES (686,'UKF Dubstep 2012','Ayah Marar','The Raver - Xilent Remix');
INSERT INTO MUSIC VALUES (687,'Undead','Hollywood Undead','Undead');
INSERT INTO MUSIC VALUES (688,'Until The Day I Die','Story Of The Year','Until The Day I Die');
INSERT INTO MUSIC VALUES (689,'Vandaag EP','Bakermat','Vandaag - Original Mix');
INSERT INTO MUSIC VALUES (690,'Vario','Savant','Splinter - Original Mix');
INSERT INTO MUSIC VALUES (691,'Vario','Savant','Living iPod - Original Mix');
INSERT INTO MUSIC VALUES (692,'Vario','Savant','Hero From The Past - Original Mix');
INSERT INTO MUSIC VALUES (693,'Vario','Savant','Ba-Da Bing! - Original Mix');
INSERT INTO MUSIC VALUES (694,'Vario','Savant','Burgertime (Savant Theme) - Original Mix');
INSERT INTO MUSIC VALUES (695,'Vario','Savant','Trust Issues - Original Mix');
INSERT INTO MUSIC VALUES (696,'Various EP','ExcisionStickybuds','Whalestep');
INSERT INTO MUSIC VALUES (697,'Vindicate','Datsik & ExcisionDatsikExcision','Vindicate');
INSERT INTO MUSIC VALUES (698,'Vitamin D','DatsikInfected MushroomJonathan Davis','Evilution');
INSERT INTO MUSIC VALUES (699,'Vitamin D','Datsik','Annihilate');
INSERT INTO MUSIC VALUES (700,'Vitamin D','DatsikDownlink','Syndrome');
INSERT INTO MUSIC VALUES (701,'Viva La Vida Or Death And All His Friends','Coldplay','Viva La Vida');
INSERT INTO MUSIC VALUES (702,'Vol. 3: The Subliminal Verses [Special Package]','Slipknot','Duality');
INSERT INTO MUSIC VALUES (703,'Voscilate / Night Goes On','Flux Pavilion','Night Goes On');
INSERT INTO MUSIC VALUES (704,'Wake Up Call Remixes','Steve AokiSidney Samson','Wake Up Call - Dantsik Mix');
INSERT INTO MUSIC VALUES (705,'Walk in the Fire','Dirtyphonics','Walk in the Fire (Original Mix)');
INSERT INTO MUSIC VALUES (706,'We Are The Night','The Chemical Brothers','Do It Again');
INSERT INTO MUSIC VALUES (707,'We Can Make The World Stop - EP','The Glitch Mob','We Can Make The World Stop');
INSERT INTO MUSIC VALUES (708,'We Can Make The World Stop - EP','The Glitch Mob','Warrior Concerto');
INSERT INTO MUSIC VALUES (709,'We Started Nothing','The Ting Tings','That''s Not My Name');
INSERT INTO MUSIC VALUES (710,'Weekend In America','Wolfgang Gartner','Illmerica');
INSERT INTO MUSIC VALUES (711,'Weekend In America','Wolfgang Gartner','The Champ');
INSERT INTO MUSIC VALUES (712,'Weekends!!! (feat. Sirah)','Skrillex','Weekends!!! - feat. Sirah');
INSERT INTO MUSIC VALUES (713,'Welcome Reality','Nero','Doomsday');
INSERT INTO MUSIC VALUES (714,'Welcome Reality','Nero','Me And You');
INSERT INTO MUSIC VALUES (715,'Welcome Reality','Nero','Crush On You');
INSERT INTO MUSIC VALUES (716,'What If EP','Fytch','What If I Told You');
INSERT INTO MUSIC VALUES (717,'What If EP','Fytch','That I Love You');
INSERT INTO MUSIC VALUES (718,'What Is Your Desire','Tantrum Desire','I Am Unicron');
INSERT INTO MUSIC VALUES (719,'What We Saw EP','Mitis','Irene (Original Mix)');
INSERT INTO MUSIC VALUES (720,'(What''s The Story) Morning Glory','Oasis','Wonderwall');
INSERT INTO MUSIC VALUES (721,'When Pigs Fly','Mason','Make You Cringe');
INSERT INTO MUSIC VALUES (722,'Whispers In The Dark','Skillet','Whispers In The Dark - Radio Edit');
INSERT INTO MUSIC VALUES (723,'Who Is Ready To Jump','Chuckie','Who Is Ready To Jump - Original Club Mix');
INSERT INTO MUSIC VALUES (724,'Who You Are','Jessie JB.o.B','Price Tag');
INSERT INTO MUSIC VALUES (725,'Wipeout','Noisestorm','Wipeout');
INSERT INTO MUSIC VALUES (726,'Without A Twist','SouleroThe Noisy Freaks','Without A Twist - The Noisy Freaks Remix');
INSERT INTO MUSIC VALUES (727,'Wolfgang Amadeus Phoenix','Phoenix','Lisztomania - Alex Metric Remix');
INSERT INTO MUSIC VALUES (728,'Wolfmother','Wolfmother','Joker And The Thief');
INSERT INTO MUSIC VALUES (729,'Won''t You (Be There) EP','Nero','Etude');
INSERT INTO MUSIC VALUES (730,'Wondering','Does It Offend You, Yeah?','Wondering - Dirtyphonics Remix');
INSERT INTO MUSIC VALUES (731,'Wraith','Torus','Wraith - Original');
INSERT INTO MUSIC VALUES (732,'Writer''s Block','Peter Bjorn And John','Young Folks');
INSERT INTO MUSIC VALUES (733,'The Wrong Kid Died','HaezerCirce','Stars Feat. Circe');
INSERT INTO MUSIC VALUES (734,'X Rated','ExcisionDatsik','Deviance - Original Mix');
INSERT INTO MUSIC VALUES (735,'Yes Yes Vindictive','Operator Please','Get What You Want');
INSERT INTO MUSIC VALUES (736,'You Don''t Know - Ninja Cuts','TTC','Travailler - Orgasmic remix');
INSERT INTO MUSIC VALUES (737,'You''ve Come a Long Way Baby','Fatboy Slim','The Rockafeller Skank');
INSERT INTO MUSIC VALUES (738,'You''ve Come A Long Way, Baby','Fatboy Slim','Right Here, Right Now');
INSERT INTO MUSIC VALUES (739,'Yup Yup','Tha New TeamWe Are Scientist','Ghouls - Tha New Team Remix');
INSERT INTO MUSIC VALUES (740,'Zeig mir wie du tanzt','Frida Gold','Zeig mir wie du tanzt - Skrillex Remix');
INSERT INTO MUSIC VALUES (741,'Zombi EP','Vudvuzela','Zombi - Original Mix');
INSERT INTO MUSIC VALUES (742,'Rage Valley EP','Knife Party','Sleaze - feat. Mistajam');
INSERT INTO MUSIC VALUES (743,'Anaconda','Nicki Minaj','Anaconda');
INSERT INTO MUSIC VALUES (744,'Hellbilly Deluxe','Rob Zombie','Living Dead Girl');
INSERT INTO MUSIC VALUES (745,'Begin Again','Knife Party','Begin Again');
INSERT INTO MUSIC VALUES (746,'Dernière Danse','Indila','Dernière danse');
INSERT INTO MUSIC VALUES (747,'Haunted House','Knife Party','EDM Death Machine');
INSERT INTO MUSIC VALUES (748,'Boneless (Remixes)','Steve AokiChris LakeTujamo','Boneless');
INSERT INTO MUSIC VALUES (749,'I Can''t Take It','Dillon Francis','I Can''t Take It');
INSERT INTO MUSIC VALUES (750,'Worlds','Porter RobinsonLemaitre','Polygon Dust');
INSERT INTO MUSIC VALUES (751,'Street Trash','Enhancer','Pas Sommeil');
INSERT INTO MUSIC VALUES (752,'Spy Games Chapter 2','PhrenikKezwik','The Kingdom - Original Mix');
INSERT INTO MUSIC VALUES (753,'Prayer In C','Lilly Wood and The PrickRobin Schulz','Prayer in C - Robin Schulz Radio Edit');
INSERT INTO MUSIC VALUES (754,'Don''t Kill the Magic','Magic!','Rude');
INSERT INTO MUSIC VALUES (755,'L''ecole Du Micro D''argent','Iam','Elle Donne Son Corps Avant Son Nom');
INSERT INTO MUSIC VALUES (756,'The Dead Symphonic EP','Zomboy','Gorilla March');
INSERT INTO MUSIC VALUES (757,'Get Wet','Krewella','Human');
INSERT INTO MUSIC VALUES (758,'The Outbreak','Zomboy','Patient Zero - Original Mix');
INSERT INTO MUSIC VALUES (759,'Get Wet','Krewella','We Go Down');
INSERT INTO MUSIC VALUES (760,'Rather Be feat. Jess Glynne','Clean BanditJess Glynne','Rather Be (feat. Jess Glynne)');
INSERT INTO MUSIC VALUES (761,'Destroid - The Invasion','Excision and Space LacesExcisionSpace Laces','Destroid 7 Bounce');
INSERT INTO MUSIC VALUES (762,'Megalithic Symphony','AWOLNATION','Sail (Borgore Pop The Sweating I''m Sailing Remix)');
INSERT INTO MUSIC VALUES (763,'Hear No Evil','Protohype','Jelly Roll');
INSERT INTO MUSIC VALUES (764,'Shower','Becky G','Shower');
INSERT INTO MUSIC VALUES (765,'Calamari Tuesday','Feed Me','No Grip');
INSERT INTO MUSIC VALUES (766,'Calamari Tuesday','Feed MeCrystal Fighters','Love Is All I Got');
INSERT INTO MUSIC VALUES (767,'Calamari Tuesday','Feed Me','Fiasco');
INSERT INTO MUSIC VALUES (768,'Calamari Tuesday','Feed Me','In The Bin');
INSERT INTO MUSIC VALUES (769,'Calamari Tuesday','Feed Me','Rat Trap');
INSERT INTO MUSIC VALUES (770,'Calamari Tuesday','Feed MeTasha Baxter','Ebb & Flow');
INSERT INTO MUSIC VALUES (771,'Hardwell Presents Revealed Vol. 5','Armin van Buuren','Ping Pong [Mix Cut] - Hardwell Remix');
INSERT INTO MUSIC VALUES (772,'Hardwell Presents Revealed Vol. 5','Marnik','Momentum [Mix Cut] - Original Mix');
INSERT INTO MUSIC VALUES (773,'Hardwell Presents Revealed Vol. 5','DeorroJ-Trick','Rambo [Mix Cut] - Hardwell Edit');
INSERT INTO MUSIC VALUES (774,'Hardwell Presents Revealed Vol. 5','Paris BlohmTaylr Renee','Left Behinds [Mix Cut] - Original Mix');
INSERT INTO MUSIC VALUES (775,'Hardwell Presents Revealed Vol. 5','Hardwell','Everybody Is In The Place [Mix Cut] - I AM Hardwell Intro Edit');
INSERT INTO MUSIC VALUES (776,'Legacy','Nicky RomeroKrewella','Legacy - Radio Edit');
INSERT INTO MUSIC VALUES (777,'Calling All Heroes - EP','Adventure Club','Thunderclap');
INSERT INTO MUSIC VALUES (778,'Calling All Heroes - EP','Adventure Club','Crash');